### ISSUE TITLE
GetDetails or GRPCException must be an array

### ISSUE THREAD

**Issue by wolfy-j** [spiral/php-grpc#33]

**Comment by everflux** [comment]
I assume this is issue related to this stack trace

```
ERRO[0003] 172.17.0.1:56204 Internal {1.69ms} /greet.HelloService/Greet worker error: EOF 
WARN[0003] Fatal error: Uncaught TypeError: Return value of Spiral\GRPC\Exception\GRPCException::getDetails() must be of the type array, object returned in /var/www/vendor/spiral/php-grpc/src/Exception/GRPCException.php:54 
WARN[0003] Stack trace:                                 
WARN[0003] #0 /var/www/vendor/spiral/php-grpc/src/Server.php(138): Spiral\GRPC\Exception\GRPCException->getDetails() 
WARN[0003] #1 /var/www/vendor/spiral/php-grpc/src/Server.php(87): Spiral\GRPC\Server->packError(Object(Spiral\GRPC\Exception\InvokeException)) 
WARN[0003] #2 /var/www/worker.php(17): Spiral\GRPC\Server->serve(Object(Spiral\RoadRunner\Worker)) 
```

**Comment by wolfy-j** [comment]
Yes. There are bug with the Exception signature.

I think it's somewhere there, busy on other projects to deal with it, any help is appreciated.
https://github.com/spiral/php-grpc/blob/master/src/ServiceWrapper.php#L113

**Comment by everflux** [comment]
Ok, I will fork the repo and have a look around.

**Comment by everflux** [comment]
I am using the release version: 1.1.0
In master my case is already fixed, missing array in ```Invoker.php```
For the ServiceWrapper I created a PR

Please release 1.1.1 once it is merged - thanks!
