### ISSUE TITLE
Undefined class or binding 'Spiral\Boot\EnvironmentInterface'

### ISSUE THREAD

**Issue by Noramarth** [spiral/php-grpc#81]
```php
Undefined class or binding 'Spiral\Boot\EnvironmentInterface'
#0 [...]/vendor/spiral/framework/src/Boot/src/helpers.php(68): spiral()
#1 [...]/app/config/database.php(37): env()
```
Makes no sense at all but from what I can find: 
```EnvironmentInterface``` is not actually bound ?

composer.json:
```json
"require": {
    "php": ">=8.0",
    "ext-curl": "*",
    "ext-zip": "*",
    "cycle/annotated": "2.3.1",
    "cycle/migrations": "1.0.10",
    "cycle/orm": "1.4.2",
    "cycle/proxy-factory": "1.3.1",
    "doctrine/cache": "1.11.3",
    "firebase/php-jwt": "v5.4.0",
    "jetbrains/phpstorm-attributes": "1.0",
    "spiral/database": "2.8.4",
    "spiral/dotenv-bridge": "2.7.2",
    "spiral/framework": "2.8.7",
    "spiral/jobs": "2.2.1",
    "spiral/migrations": "2.2.0",
    "spiral/php-grpc": "1.5.0",
    "spiral/prototype": "2.7.2",
    "spiral/roadrunner": "1.9.2",
    "php-di/php-di": "^6.3.0",
    "grpc/grpc": "1.42.0"
  },
```

**Comment by rustatian** [comment]
Hey @Noramarth, thanks for the report. Keep in mind, that the `php-grpc` package is deprecated, please, consider updating to v2 (https://github.com/spiral/roadrunner-grpc).

Could you please clarify, how this issue is related to the `php-grpc` repository?

**Comment by Noramarth** [comment]
hey @rustatian Upgrading to roadrunner-grpc turned out to be a huge task so we reverted everything :) But if you can give me some pointers that would be amazing!

Also, now that you mention it, this bug should have been posted in the framework repo. My mistake. Sorry

**Comment by rustatian** [comment]
Np, I'll move it )
